<?php

return [
    'en' => [
        '🎰 Welcome to Lucky Million!',
        '🍀 Ready to spin and win?',
        '💰 Big jackpots await you!',
        '🌀 Let the reels roll!',
        '💎 Feel the thrill of every spin!',
        '🎉 Today could be your lucky day!',
        '🏆 Spin smart, win big!',
        '🎲 May the slots be ever in your favor!',
        '🎮 Game on! Good luck!',
        '🤑 Claim your spins now!',
        '💫 Start your lucky streak!',
        '📈 Keep spinning, keep climbing!',
        '🔥 The reels are hot today!',
        '🔁 Spin again, win again!',
        '🎊 Welcome! Let’s chase that jackpot!',
        '🚀 Power up your game today!',
        '🌟 You’re destined for greatness!',
        '🎭 Every spin tells a story.',
        '💼 Time to make a fortune!',
        '📦 Daily rewards waiting for you!',
        '🎯 Target the bonus round!',
        '💌 Thanks for joining us!',
        '📍 Spin from anywhere, anytime!',
        '📜 History remembers high rollers!',
        '🎮 Pick your lucky slot and go!',
        '🎲 Fortune is calling you!',
        '🎁 Free spins? Yes, please!',
        '🛸 Fly into the reels of fortune!',
        '🧧 Good luck with your first spin!',
        '👑 Rule the slots like a pro!',
        '🎠 The fun never stops here!',
        '🎧 Play your way, your style!',
        '📣 Join thousands of winners!',
        '📊 Stats say... you’re next!',
        '📅 Your daily dose of luck is here!',
        '🕹️ Tap, spin, and celebrate!',
        '📞 Destiny is one spin away!',
        '🎉 Your jackpot awaits!',
        '🧨 Blast off to bonus rounds!',
        '🌈 Every spin is a new chance!',
        '🗺️ Explore every slot world!',
        '📤 Don’t forget your daily bonus!',
        '🧲 Attracting luck right now...',
        '🎟️ You’ve got a golden ticket!',
        '🔓 Unlock rewards instantly!',
        '🚦 All lights green. SPIN NOW!',
        '🥇 Play hard, win harder!',
        '🚨 Alert: Big wins detected!',
        '🔊 Spin, spin, spin again!',
        '💖 Welcome to our lucky family!',
        '💬 Need help? Just type /help!',
        '🦾 Let the game begin!',
        '🎬 Spin your own story!',
        '🏝️ Escape into the reels!',
        '🧮 Lucky numbers activated!',
        '🎫 New missions are live!',
        '📌 Don’t stop now!',
        '🪄 Magic starts with a spin!',
        '🧠 Stay smart, spin smarter!',
        '📍 You’re in the zone now!',
        '🌐 Join players worldwide!',
        '📌 Keep calm and spin on.',
        '🧡 Enjoy every spin!',
        '🌟 Rewards are closer than you think.',
        '🎢 Welcome to the reel rush!',
        '🏦 Big wins make big days!',
        '💡 Play more, learn more, win more!',
        '🎉 Win or learn. Either way, enjoy!',
        '🎮 100+ games waiting for you!',
        '🥂 Cheers to lucky spins!',
        '🚧 Caution: Winning zone ahead!',
        '🌠 Make a wish, spin the reels!',
        '🛍️ Bonus round inside!',
        '🎯 You’re locked on jackpot!',
        '⚡ Charged with excitement!',
        '🎁 Spin to reveal your gift!',
        '🗓️ Today’s bonus unlocked!',
        '🌟 Tap into pure fun!',
        '💸 Free coins inside!',
        '🎭 Unmask your luck!',
        '🛒 Don’t forget to collect coins!',
        '🚪 Enter the world of fortune!',
        '🛫 Start your jackpot journey!',
        '🎤 Let your spin sing!',
        '🛡️ You’ve got luck protection!',
        '🎞️ New slot just released!',
        '🦄 Bring magic to your reels!',
        '🌋 Epic spins ahead!',
        '🍒 Slot fever begins now!',
        '🎨 Design your own winning streak!',
        '🔮 Let luck guide you!',
        '🔐 Unlock hidden features!',
        '🕹️ Enjoy seamless spinning!',
        '🌞 Shine bright, spin brighter!',
        '🧧 Bonus boost available now!',
        '🧱 Build your win streak!',
        '🥳 You’re our lucky guest today!',
        '🫧 Float into the fortune zone!',
        '💿 Classic slots, endless joy!',
        '🌐 One world. Millions of reels!',
        '🥰 You’re in good hands here!',
        '🎩 Welcome, slot master!',
        '📢 Spin loud, win proud!',
        '🏁 Game begins now!',
    ],
    'mm' => [
        '🎰 Lucky Million မှကြိုဆိုပါတယ်!',
        '🍀 မင်္ဂလာရှိစေပါတယ်။ အနိုင်တွေစောင့်နေပါတယ်။',
        '💰 ကြီးမားတဲ့ဆုကြေးတွေရှိပါတယ်။',
        '🌀 စတင်လှည့်လိုက်ပါ!',
        '💎 လှည့်တိုင်းမှာ စိတ်လှုပ်ရှားစရာ!',
        '🎉 ဒီနေ့က သင့်နေ့ဖြစ်နိုင်ပါတယ်။',
        '🏆 အားထုတ်လှည့်ပြီး ဆုကြီးရယူပါ။',
        '🎲 မင်္ဂလာကံကောင်းပါစေ!',
        '🎮 ကစားစရာအသင့်ဖြစ်ပါပြီ!',
        '🤑 စပင်ယူဖို့ မမေ့နဲ့!',
        '💫 သင့်ကံကောင်းစဉ်စတင်ပါပြီ။',
        '📈 လှည့်ပြီး ဆုကြေးတွေလည်းတက်လာတယ်။',
        '🔥 ဒီနေ့ ရီးလ်တွေ အရမ်းပူနေပြီ!',
        '🔁 ထပ်လှည့်ပြီး ထပ်နိုင်!',
        '🎊 Jackpot ချန်သက်ရန် ပြင်ဆင်ပါ!',
        '🚀 စွမ်းအားမြှင့်တင်ပြီး Game စလှည့်!',
        '🌟 သင့်ကံကောင်းမှန်ပါစေ။',
        '🎭 လှည့်တိုင်းမှာ စကားပြောတစ်ခုရှိတယ်။',
        '💼 ကံကောင်းမှုအတွက် အချိန်ရောက်ပြီ!',
        '📦 နေ့စဉ်ဆုကြေးရှိပါတယ်။',
        '🎯 Bonus Round ဝင်ဖို့ ကြိုးစားပါ။',
        '💌 ကျွန်တော်တို့ကို ရွေးချယ်တဲ့အတွက် ကျေးဇူးတင်ပါတယ်။',
        '📍 မည်သည့်နေရာမှမဆို လှည့်နိုင်ပါတယ်။',
        '📜 အောင်မြင်သူများ၏ မှတ်တမ်းသစ်!',
        '🎮 သင့်ရဲ့ကံကောင်း Game ကိုရွေးပါ။',
        '🎲 ကံကောင်းမှုဟာ သင့်ကိုခေါ်နေပြီ။',
        '🎁 လက်ခုပ်ခေါင်း စပင်တွေရှိတယ်!',
        '🛸 ဝင်ပြီး ဆုကြေးတွေဖော်ထုတ်လိုက်ပါ!',
        '🧧 ပထမလှည့်မှာ ဆုကြေးတစ်ခု ရမယ်ဆိုတာယုံကြည်ပါ!',
        '👑 Slots တွေရဲ့ မင်းသားဖြစ်ပါစေ!',
        '🎠 အချိန်တိုင်းက အပန်းဖြေစရာ!',
        '🎧 သင့်စတိုင်နဲ့ ကစားပါ!',
        '📣 အောင်မြင်သူများနှင့် ပူးပေါင်းပါ!',
        '📊 ဒီတစ်ခါမှာ သင်နိုင်ဖို့ရှိတယ်။',
        '📅 နေ့စဉ်ကံကောင်းမှု စတင်ပါပြီ!',
        '🕹️ ထိ, လှည့်, အနိုင်ယူ!',
        '📞 တစ်လှည့်တည်းနဲ့ ပြောင်းလဲနိုင်တယ်။',
        '🎉 Jackpot မျှော်လင့်ချက်ရှိတယ်!',
        '🧨 Bonus ရယူဖို့ ချက်ချင်းစတင်!',
        '🌈 တစ်လှည့်လှည့်တိုင်းမှာ အခွင့်အလမ်း!',
        '🗺️ Slot အသစ်တွေ ရှာဖွေလိုက်ပါ!',
        '📤 နေ့စဉ် ဆုကြေးယူဖို့ မမေ့နဲ့!',
        '🧲 ကံကောင်းမှုဆွဲယူနေသည်...',
        '🎟️ Golden Ticket ရှိပါတယ်။',
        '🔓 Bonus Feature ပွင့်လင်းနေပြီ!',
        '🚦 အစပျိုးပြီး Spin လုပ်!',
        '🥇 ကစားပြီး အောင်မြင်ပါ!',
        '🚨 Big Win ရှိနေပါတယ်!',
        '🔊 လှည့်! နိုင်! ထပ်လှည့်!',
        '💖 သင့်အတွက် ဝင်ရောက်လာသူ!',
        '💬 /help ကို စမ်းကြည့်ပါ။',
        '🦾 Game စဖို့ အဆင်သင့်!',
        '🎬 အောင်မြင်မှုစတင်ပါ!',
        '🏝️ Slots ကမ္ဘာထဲ ဝင်ကြည့်ပါ။',
        '🧮 Lucky Number တွေရော?',
        '🎫 Mission အသစ်တွေစတင်!',
        '📌 မနားပါနဲ့!',
        '🪄 မ်က်စိဖွင့်ပြီး ထပ်လှည့်!',
        '🧠 Smart လှည့်တဲ့သူက အနိုင်ရ!',
        '📍 Zone ထဲ ဝင်သွားပြီ!',
        '🌐 ကမ္ဘာတစ်ဝှမ်းက ကစားသူတွေနဲ့!',
        '📌 Calm ဖြစ်ပြီး spin လုပ်!',
        '🧡 Slot Gaming က ပျော်စရာ!',
        '🌟 ဆုကြေးက နီးလာပြီ!',
        '🎢 Spin Rush က မစခင်!',
        '🏦 ကြီးမားတဲ့ Win တွေ စောင့်နေပါတယ်!',
        '💡 အနည်းငယ်ကနေ စတင်ပါ!',
        '🎉 အောင်မြင်တာမျိုး အမြဲ မေ့မရ!',
        '🎮 100+ Game တွေစောင့်နေတာ!',
        '🥂 Lucky Player ဖြစ်ပါစေ!',
        '🚧 Warning! Win များနီးလာပြီ!',
        '🌠 Slot Spin မှာ ဆုတွေဖျော်ပါ!',
        '🛍️ Bonus တွေရှိနေပြီ!',
        '🎯 Jackpot တည်နေရာကို ငြိမ်းစွာဖောက်!',
        '⚡ အာနိသင်ပြည့်!',
        '🎁 Gift တစ်ခုဖော်ပြပါ!',
        '🗓️ Daily Gift ကိုယူလိုက်ပါ!',
        '🌟 ပျော်ရွှင်မှုအစ!',
        '💸 Coins များစွာ ရှိပါတယ်!',
        '🎭 Luck ကိုဖော်ထုတ်ပါ!',
        '🛒 Coins စုဖို့မမေ့နဲ့!',
        '🚪 Slot ခန်းမထဲ ဝင်လိုက်ပါ!',
        '🛫 Jackpot ရယူဖို့စတင်ပါ!',
        '🎤 Spin မှာသံမဏိ!',
        '🛡️ မနာခံဘဲ Spin လုပ်!',
        '🎞️ Slot အသစ်ထပ်မံ!',
        '🦄 Slot ကို မျိုးကွဲပေးပါ!',
        '🌋 Epic Win ရဖို့အချိန်!',
        '🍒 Classic Slot Fever!',
        '🎨 အောင်မြင်မှုဖန်တီးပါ!',
        '🔮 Luck နဲ့ လှည့်ပါ!',
        '🔐 Features တွေဖွင့်!',
        '🕹️ Smooth Game Play!',
        '🌞 ရောင်ခြည်တောက်တယ်!',
        '🧧 Boost Bonus ရယူလိုက်!',
        '🧱 Win Streak တည်ဆောက်ပါ!',
        '🥳 ဒီနေ့က သင့်နေ့!',
        '🫧 Slot တိုင်းမှာ သဲသဲလှုပ်!',
        '💿 Classic Slot တွေရဲ့ နိမိတ်!',
        '🌐 Millionaire Player တစ်ယောက်ဖြစ်ပါစေ!',
        '🥰 Game ပေါင်းများစွာ!',
        '🎩 Reel Master ဟုတ်လား?',
        '📢 Spin တုန်းမှာ ဘာတွေလုပ်မလဲ!',
        '🏁 Let’s Go!',
    ],
    'account_created' => [
        'en' => [
            '✅ Your account has been created successfully!',
            "🎉 Welcome aboard! You're now part of the Lucky Million family.",
            "🙌 Account setup complete. Let's spin and win!",
            '🆕 Your Lucky Million account is now active!',
            '📲 Registration successful — enjoy all features!',
        ],
        'mm' => [
            '✅ သင့်အကောင့်ကိုအောင်မြင်စွာဖန်တီးပြီးပါပြီ။',
            '🎉 ကြိုဆိုပါတယ်။ Lucky Million မိသားစုထဲသို့ ဝင်ရောက်ပါပြီ။',
            '🙌 အကောင့်ဖွင့်ခြင်းအောင်မြင်ပါပြီ။ Spin လုပ်ဖို့အချိန်ပါ!',
            '🆕 သင့် Lucky Million အကောင့် အသုံးပြုနိုင်ပြီ!',
            '📲 စာရင်းသွင်းမှုအောင်မြင်ပါပြီ။ အဆင်ပြေစွာ ကစားနိုင်ပါတယ်။',
        ],
    ],

    'events' => [
        'account_deactivated' => [
            'en' => [
                '⚠️ Your account has been deactivated. Contact support if this is a mistake.',
                '🔒 Account access has been restricted. Please reach out to the admin.',
            ],
            'mm' => [
                '⚠️ သင့်အကောင့်ကိုပိတ်လိုက်ပါပြီ။ မမှန်ဘူးလို့ထင်ရင် admin ကိုဆက်သွယ်ပါ။',
                '🔒 သင့်အကောင့်အသုံးပြုခွင့်ကို ခေတ္တပိတ်ထားပါတယ်။ Admin ကိုဆက်သွယ်ပါ။',
            ],
        ],
        'password_changed' => [
            'en' => [
                '🔐 Your password has been changed successfully.',
                '✅ Password updated. Keep your login details safe.',
            ],
            'mm' => [
                '🔐 သင့်စကားဝှက်ကိုအောင်မြင်စွာပြောင်းလဲပြီးပါပြီ။',
                '✅ စကားဝှက်အသစ်ကို အသုံးပြုနိုင်ပြီ။ လုံခြုံစွာထားပါ။',
            ],
        ],
        'balance_updated' => [
            'en' => [
                '💰 Your balance has been updated.',
                '📈 Balance changed. Check your wallet for details.',
            ],
            'mm' => [
                '💰 သင့်အကောင့်လက်ကျန်ကို အပ်ဒိတ်လုပ်ပြီးပါပြီ။',
                '📈 ငွေလက်ကျန်ပြောင်းလဲသွားပါပြီ။ အသေးစိတ်ကြည့်ပါ။',
            ],
        ],
        'referral_joined' => [
            'en' => [
                '🎉 Someone joined using your referral link!',
                '🙌 A new player has registered via your referral.',
            ],
            'mm' => [
                '🎉 သင့် referral link ဖြင့်အသစ်ဝင်လာသူရှိပါပြီ။',
                '🙌 သင့်အကြောင်းပြန်ဖြင့် အသစ်စာရင်းသွင်းသူတစ်ဦးရှိပါပြီ။',
            ],
        ],
    ],

];
