<?php

namespace App\Enums;

enum CurrencyCode: string
{
    case AED = 'AED';
    case AMD = 'AMD';
    case AOA = 'AOA';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AZN = 'AZN';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BND = 'BND';
    case BRL = 'BRL';
    case CAD = 'CAD';
    case CHF = 'CHF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case CRC = 'CRC';
    case CZK = 'CZK';
    case DKK = 'DKK';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FRF = 'FRF';
    case GBP = 'GBP';
    case GC = 'GC';
    case GTQ = 'GTQ';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case INR = 'INR';
    case IRR = 'IRR';
    case JPY = 'JPY';
    case KES = 'KES';
    case KHR = 'KHR';
    case KRW = 'KRW';
    case KSH = 'KSH';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case MAD = 'MAD';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MXN = 'MXN';
    case MYR = 'MYR';
    case NGN = 'NGN';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NTD = 'NTD';
    case NZD = 'NZD';
    case PEN = 'PEN';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PTI = 'PTI';
    case PTV = 'PTV';
    case PYG = 'PYG';
    case RON = 'RON';
    case RUB = 'RUB';
    case SAR = 'SAR';
    case SC = 'SC';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case THB = 'THB';
    case TND = 'TND';
    case TRY = 'TRY';
    case TWD = 'TWD';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case USDT = 'USDT';
    case UZS = 'UZS';
    case VES = 'VES';
    case VND = 'VND';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';
    case BOB = 'BOB';
    case UYU = 'UYU';
    case XAF = 'XAF';
    case CDF = 'CDF';
    case GYD = 'GYD';
    case TOP = 'TOP';
    // 1:1000 and 1:100 special cases
    case PYG2 = 'PYG2'; // 1:1000
    case COP2 = 'COP2'; // 1:1000
    case IDR2 = 'IDR2'; // 1:1000
    case IRR2 = 'IRR2'; // 1:1000
    case KHR2 = 'KHR2'; // 1:1000
    case KRW2 = 'KRW2'; // 1:1000
    case LAK2 = 'LAK2'; // 1:1000
    case LBP2 = 'LBP2'; // 1:1000
    case MMK2 = 'MMK2'; // 1:1000
    case UZS2 = 'UZS2'; // 1:1000
    case VND2 = 'VND2'; // 1:1000
    case MMK3 = 'MMK3'; // 1:100
}
